config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root  "home#top"
  get  "home/about" => "home#about"
resources :searchs, only: [:index]
resources :users, only: [:index, :show, :edit, :update] do
  	get "follows"
  	get "follower"
  end
  	post "follow/:id" => "relationships#follow", as: "follow"
  	post "unfollow/:id" => "relationships#unfollow", as: "unfollow"

resources :bikes do
	resources :comments, only: [:create, :destroy]
	resource :bookmarks, only: [:create, :destroy]
  resource :likes, only: [:create, :destroy]
end
  get "bookmarks/index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bike.rb
class Bike < ApplicationRecord
	belongs_to :user
	has_many :likes, dependent: :destroy
	has_many :bookmarks, dependent: :destroy
	has_many :comments, dependent: :destroy
	has_many :tagmaps, dependent: :destroy
	has_many :tags, through: :tagmaps
	attachment :image

	validates :image, presence: true
	validates :title, presence: true,length: { maximum: 300 }

	def like_by?(user)
		likes.where(user_id: user.id).exists?
	end

	def bookmark_by?(user)
		bookmarks.where(user_id: user.id).exists?
	end

	def Bike.search(search, user_or_bike)
	    if user_or_bike == "2"
	      Bike.where(["title LIKE ?", "%#{search}%"])
	    else
	      all
	    end
	 end
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :user
  belongs_to :bike
  validates :user_id, uniqueness: {scope: :bike_id}
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :bike
  validates :comment, presence: true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :bike
end

app/models/relationship.rb
class Relationship < ApplicationRecord
	belongs_to :follower, class_name: "User"
	belongs_to :followed, class_name: "User"
end

app/models/tag.rb
class Tag < ApplicationRecord
	has_many :tagmaps, dependent: :destroy
	has_many :bikes, through: :tagmaps
end

app/models/tagmap.rb
class Tagmap < ApplicationRecord
	belongs_to :bike
	belongs_to :tag
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :bikes, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  has_many :bookmarks_bikes, through: :bookmarks, source: :bike
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :following_user, through: :follower, source: :followed
  has_many :follower_user, through: :followed, source: :follower
  attachment :profile_image

 def follow(user_id)
 	follower.create(followed_id: user_id)
 end

 def unfollow(user_id)
 	follower.find_by(followed_id: user_id).destroy
 end

 def following?(user)
 	following_user.include?(user)
 end

 def User.search(search, user_or_bike)
    if user_or_bike == "1"
     User.where(["name LIKE ? OR bike_name LIKE ?", "%#{search}%", "%#{search}%"])
    else
      all
    end
 end

  validates :name, presence: true,length: { minimum: 2, maximum: 20 }
  validates :bike_name, presence: true,length: { minimum: 2, maximum: 20 }

end

app/controllers/bikes_controller.rb
class BikesController < ApplicationController
	before_action :authenticate_user!
	def index
		@bikes = params[:tag_id].present? ? Tag.find(params[:tag_id]).bikes.page(params[:page]).per(5) : Bike.all.includes(:user).page(params[:page]).per(5).order(created_at: :desc)
	end

	def new
		@newbike = Bike.new
	end

	def show
		@bike = Bike.find(params[:id])
		@comment = Comment.new
		@comments = @bike.comments
	end

	def edit
		@bike = Bike.find(params[:id])
		if @bike.user != current_user
			redirect_to bike_path
		end
	end

	def create
		@newbike = Bike.new(bike_params)
		@newbike.user_id = current_user.id
		if @newbike.save
			flash[:notice] = "投稿しました！"
			redirect_to bikes_path
		else
			render :new
		end
	end

	def update
		@bike = Bike.find(params[:id])
		@user = current_user
		if @bike.update(bike_params)
			flash[:notice] = "編集しました！"
			redirect_to bike_path(@bike)
		else
			render :edit
		end
	end

	def destroy
		@bike = Bike.find(params[:id])
		@bike.destroy
		redirect_to bikes_path, notice: "削除しました！"
	end

	private
	def bike_params
		params.require(:bike).permit(:image, :title, tag_ids: [])
	end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def top
	end
	def about
	end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @bike = Bike.find(params[:bike_id])
    @like =current_user.likes.new(bike_id: @bike.id)
    @like.save
    render :like
  end

  def destroy
    @bike = Bike.find(params[:bike_id])
    @like = current_user.likes.find_by(bike_id: @bike.id)
    @like.destroy
    render :like
  end

end

app/controllers/searchs_controller.rb
class SearchsController < ApplicationController
	before_action :authenticate_user!
	def index
		@user_or_bike = params[:option]
		if @user_or_bike == "1"
			@users = User.all.search(params[:search], @user_or_bike).page(params[:page]).per(10)
		else
			@bikes = Bike.all.search(params[:search], @user_or_bike).page(params[:page]).per(5)
		end
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!
	def show
		@user = User.find(params[:id])
		@bikes = @user.bikes.order(created_at: :desc).page(params[:page]).per(5)
	end

	def index
		@search = User.ransack(params[:q])
		@users = @search.result(distinct: true).page(params[:page]).per(10)
	end

	def edit
		@user = User.find(params[:id])
		if @user != current_user
			redirect_to user_path
		end
	end

	def update
		@user = User.find(params[:id])
		@user = current_user
		if @user.update(user_params)
			flash[:notice] = "編集しました！"
			redirect_to user_path(current_user)
		else
			render :edit
		end
	end

	def follows
		@user = User.find(params[:user_id])
		@users = User.page(params[:page]).per(10)
	end

	def follower
		@user = User.find(params[:user_id])
		@users = User.page(params[:page]).per(10)
	end

	private
	def user_params
		params.require(:user).permit(:user_id, :name, :bike_name, :profile_image)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bikes_helper.rb
module BikesHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/searchs_helper.rb
module SearchsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/bikes/edit.html.erb
<%= render 'layouts/errors', obj: @bike %>

<div class="row">
	<div class="col-xs-offset-3"><h2 class="title col-xs-3">投稿編集画面</h2></div>
</div><br>

<div class="postedit">
<%= form_for(@bike) do |f| %>
<div class="row">
	<div class="postimage">
            <%= f.attachment_field :image, class: "col-xs-offset-2"%><br>

		<div class="field">
			<%= f.text_area :title, placeholder: "内容を入力", size: "50x10" %>
		</div><br>

		<div class="check_box">
			<p>ジャンル</p>
			<%= f.collection_check_boxes(:tag_ids, Tag.all, :id, :tag_name) do |t| %>
				<div>
				<%= t.label do %>
				<%= t.check_box %>
				<%= t.text %>
				<% end %>
				</div>
			<% end %>
		</div>
		<br>

		<div class="actions">
			<%= f.submit "変更を保存", class: "btn btn-primary col-xs-4 col-xs-offset-4" %>
		</div>
	</div>
</div>
<% end %>
</div>

app/views/bikes/index.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
	<div class="col-xs-offset-3"><h2 class="title col-xs-3">投稿一覧画面</h2>
	</div>
	<h3 class="col-xs-1">
			<%= form_tag bikes_path, method: :get do %>
			<%= select_tag :tag_id,options_from_collection_for_select(Tag.all, :id, :tag_name, params[:tag_id]),
			{
			prompt: 'タグで絞り込み検索',
			onchange: 'submit(this.form);'
			}
			%>
	    <% end %>
	</h3>
</div><br>

<% @bikes.each do |b| %>
<div class="postlist">
<div class="row">
		<div class="img">
			<%= link_to bike_path(b.id) do %>
			<%= image_tag attachment_url(b, :image, :fill, 500, 500, format: "jpg") %>
			<% end %>
		</div>

		<div class="col-xs-offset-2">
			<!-- コメント -->
			<div class="inline-block">
				<span class="glyphicon glyphicon-comment" aria-hidden="true"></span>
				<%= b.comments.count %>
			</div>
			<!-- いいね -->
			<div class="inline-block" id ="likes_area_<%= b.id %>">
				<%= render partial: "likes/like", locals: {like: b, bike: b} %>
			</div>
			<!-- お気に入り -->
			<div class="inline-block" id="bookmark_area_<%= b.id %>">
				<%= render partial: "bookmarks/bookmark", locals: {bookmark: b, bike: b} %>
			</div>
		</div>
		<!-- フォロー -->
		<div class="col-xs-offset-8">
			<%if current_user != b.user %>
			<% if current_user.following?(b.user) %>
				<%= link_to "フォロー外す",unfollow_path(b.user),method: :post, class: "btn btn-primary" %>
				<% else %>
				<%= link_to "フォローする",follow_path(b.user),method: :post, class: "btn btn-success" %>
			<% end %>
			<% end %>
		</div>

		<div class="col-xs-offset-2">
			<p>ジャンル</p>
			<% b.tags.each do |t| %>
			   ・<%= t.tag_name %>
			<% end %><br>
			<h4>内容</h4>
			<%= b.title %>
		</div><br>

		<div class="col-xs-offset-1">
			<%= link_to user_path(b.user.id) do %>
			<%= image_tag attachment_url(b.user, :profile_image, :fill, 100, 100, format: "jpg", fallback: "no_image.jpg") %>
			<% end %>
		</div><br>

		<div class="col-xs-offset-1">
			<p>名前:
			<%= b.user.name %></p>
			<p>車種:
			<%= b.user.bike_name %></p>
		</div>
</div>
</div>
<% end %>
<div class="col-xs-offset-3">
	<%= paginate @bikes %>
</div>

app/views/bikes/new.html.erb
<%= render 'layouts/errors', obj: @newbike %>

<div class="row">
	<div class="col-xs-offset-3"><h2 class="title col-xs-3">投稿画面</h2></div>
</div><br>

<div class="postform">
<%= form_for(@newbike) do |f| %>
<div class="row">
	<div class="postimage">
            <%= f.attachment_field :image, class: "col-xs-offset-2"%><br>

		<div class="field">
			<%= f.text_area :title, placeholder: "内容を入力", size: "50x10" %>
		</div><br>

		<div class="check_box">
			<p>ジャンル</p>
			<%= f.collection_check_boxes(:tag_ids, Tag.all, :id, :tag_name) do |t| %>
				<div>
				<%= t.label do %>
				<%= t.check_box %>
				<%= t.text %>
				<% end %>
				</div>
			<% end %>
		</div>
		<br>

		<div class="actions">
			<%= f.submit "投稿", class: "btn btn-primary col-xs-4 col-xs-offset-4" %>
		</div>
	</div>
</div>
<% end %>
</div>

app/views/bikes/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
	<div class="col-xs-offset-3"><h2 class="title col-xs-3">投稿詳細画面</h2></div>
</div><br>

<div class="postdetail">

<div class="row">
<% if current_user == @bike.user %>
	<div class="col-xs-2 col-xs-offset-8">
	<%= link_to "編集", edit_bike_path, class: "btn btn-success"%>
	</div>
	<div class="col-xs-2">
	<%= link_to "削除", bike_path, class: "btn btn-danger", method: :delete, "data-confirm" => "本当に削除しますか？" %>
	</div>
<% end %>
</div><br>

<div class="row">
		<div class="img">
			<%= image_tag attachment_url(@bike, :image, :fill, 500, 500, format: "jpg") %>
		</div>

		<div class="col-xs-offset-2">
			<!-- いいね -->
			<div class="inline-block" id="likes_area_<%= @bike.id %>">
				<%= render partial: "likes/like", locals: {like: @like, bike: @bike} %>
			</div>
		</div>
		<!-- フォロー -->
		<div class="col-xs-offset-8">
			<%if current_user != @bike.user %>
			<% if current_user.following?(@bike.user) %>
				<%= link_to "フォロー外す",unfollow_path(@bike.user),method: :post, class: "btn btn-primary" %>
				<% else %>
				<%= link_to "フォローする",follow_path(@bike.user),method: :post, class: "btn btn-success" %>
			<% end %>
			<% end %>
		</div>

		<div class="col-xs-offset-2">
			<p>ジャンル</p>
			<% @bike.tags.each do |t| %>
			   ・<%= t.tag_name %>
			<% end %><br>
			<h4>内容</h4>
			<%= @bike.title %>
		</div><br>

		<div class="col-xs-offset-1">
			<%= image_tag attachment_url(@bike.user, :profile_image, :fill, 100, 100, format: "jpg", fallback: "no_image.jpg") %>
		</div><br>

		<div class="col-xs-offset-1">
			<p>名前:
			<%= @bike.user.name %></p>
			<p>車種:
			<%= @bike.user.bike_name %></p>
		</div>
</div>

<!-- コメント機能 -->
<div class="row">
	<div class="col-xs-12">
		<h4 class="col-xs-offset-1">コメント一覧</h4>
		<div id="comments_area">
		<%= render partial: "comments/comment",locals: {comments: @comments} %>
		</div>
		<div class="col-xs-4 col-xs-offset-7">
		<%= render partial: "comments/form",locals: {comment: @comment, bike: @bike } %>
		</div>
	</div>
</div>

</div>

app/views/likes/_like.html.erb
<% if bike.like_by?(current_user) %>
<%= link_to bike_likes_path(bike),method: :delete, remote: true do %>
<span class="glyphicon glyphicon-heart" aria-hidden="true"></span>
<% end %>
<%= bike.likes.count %>
<% else %>
<%= link_to bike_likes_path(bike),method: :post, remote: true do %>
<span class="glyphicon glyphicon-heart-empty" aria-hidden="true"></span>
<% end %>
<%= bike.likes.count %>
<% end %>

app/views/likes/like.js.erb
$("#likes_area_<%= @bike.id %>").html("<%= j(render 'like', {like: @like, bike: @bike}) %>")
// id="likes_area"を書き換える処理
// @likeをローカル変数likeに入れる

app/views/users/edit.html.erb
<%= render 'layouts/errors', obj: @user %>

<div class="row">
	<div class="col-xs-offset-3"><h2 class="title col-xs-3">ユーザー編集画面</h2></div>
</div><br>

<div class="useredit">
<%= form_for(@user) do |f| %>
<div class="row">
	<div class="userimage">
			<%= image_tag attachment_url(@user, :profile_image, :fill, 100, 100, format: "jpg", fallback: "no_image.jpg") %>
            <%= f.attachment_field :profile_image, class: "col-xs-offset-4" %><br>
		<div class="field">
			<%= f.text_field :name, placeholder: "名前を入力" %>
		</div><br>

		<div class="field">
			<%= f.text_field :bike_name, placeholder: "車種を入力" %>
		</div><br>

		<div class="actions">
			<%= f.submit "変更を保存", class: "btn btn-primary col-xs-4 col-xs-offset-4" %>
		</div>
	</div>
</div>
<% end %>
</div>

app/views/users/follower.html.erb
<div class="row">
	<div class="col-xs-offset-1"><h2 class="title col-xs-3">フォロワー一覧画面</h2></div>
</div><br>

<div class="followerlist">
<div class="row">
	<div class="col-xs-9 col-xs-offset-2">
		<table class="table table-hov">
			<thead>
			<tr>
				<th></th>
				<th>名前</th>
				<th>車種</th>
			</tr>
			</thead>
			<tbody>
				<% @user.follower_user.each do |u| %>
				<tr>
					<td>
					<%= link_to user_path(u.id) do %>
					<%= image_tag attachment_url(u, :profile_image, :fill, 100, 100, format: "jpg", fallback: "no_image.jpg") %>
					<% end %>
					</td>
					<td><%= u.name %></td>
					<td><%= u.bike_name %></td>
					<td>フォロー数:<%= u.follower.count %><br>
					フォロワー数:<%= u.followed.count %>
					</td>
					<td><%if current_user != u %>
					<% if current_user.following?(u) %>
					<%= link_to "フォロー外す",unfollow_path(u),method: :post, class: "btn btn-primary" %>
					<% else %>
					<%= link_to "フォローする",follow_path(u),method: :post, class: "btn btn-success" %>
					<% end %>
					<% end %>
					</td>
				</tr>
			<% end %>
			</tbody>
		</table>
<%= paginate @users %>
</div>
</div>
</div>

app/views/users/follows.html.erb
<div class="row">
	<div class="col-xs-offset-1"><h2 class="title col-xs-3">フォロー一覧画面</h2></div>
</div><br>

<div class="followlist">
<div class="row">
	<div class="col-xs-9 col-xs-offset-2">
		<table class="table table-hov">
			<thead>
			<tr>
				<th></th>
				<th>名前</th>
				<th>車種</th>
			</tr>
			</thead>
			<tbody>
				<% @user.following_user.each do |u| %>
				<tr>
					<td>
					<%= link_to user_path(u.id) do %>
					<%= image_tag attachment_url(u, :profile_image, :fill, 100, 100, format: "jpg", fallback: "no_image.jpg") %>
					<% end %>
					</td>
					<td><%= u.name %></td>
					<td><%= u.bike_name %></td>
					<td>フォロー数:<%= u.follower.count %><br>
					フォロワー数:<%= u.followed.count %>
					</td>
					<td><%if current_user != u %>
					<% if current_user.following?(u) %>
					<%= link_to "フォロー外す",unfollow_path(u),method: :post, class: "btn btn-primary" %>
					<% else %>
					<%= link_to "フォローする",follow_path(u),method: :post, class: "btn btn-success" %>
					<% end %>
					<% end %>
					</td>
				</tr>
			<% end %>
			</tbody>
		</table>
<%= paginate @users %>
</div>
</div>
</div>

app/views/users/index.html.erb
<div class="row">

<div class="col-xs-offset-1">
	<h2 class="title col-xs-3">ユーザー一覧画面</h2>
</div>


</div><br>

<div class="userlist">
<div class="row">
	<div class="col-xs-9 col-xs-offset-2">
		<table class="table table-hov">
			<thead>
				<div class="col-xs-6">
					<h4>
						<%= search_form_for @search do |f| %>
						  <%= f.search_field :name_or_bike_name_cont, placeholder: "ユーザー検索" %>
						  <%= f.submit "search" %>
						<% end %>
					</h4>
				</div>
				<tr>
					<th></th>
					<th>名前</th>
					<th>車種</th>
				</tr>
				</thead>
				<tbody>
					<% @users.each do |u| %>
					<tr>
						<td>
						<%= link_to user_path(u.id) do %>
						<%= image_tag attachment_url(u, :profile_image, :fill, 100, 100, format: "jpg", fallback: "no_image.jpg") %>
						<% end %>
						</td>
						<td><%= u.name %></td>
						<td><%= u.bike_name %></td>
						<td>フォロー数:<%= u.follower.count %><br>
						フォロワー数:<%= u.followed.count %>
						</td>
						<td><%if current_user != u %>
						<% if current_user.following?(u) %>
						<%= link_to "フォロー外す",unfollow_path(u),method: :post, class: "btn btn-primary" %>
						<% else %>
						<%= link_to "フォローする",follow_path(u),method: :post, class: "btn btn-success" %>
						<% end %>
						<% end %>
						</td>
					</tr>
				<% end %>
			</tbody>
		</table>
<%= paginate @users %>
</div>
</div>
</div>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
<div class="col-xs-offset-1">
	<h2 class="title col-xs-3">マイページ</h2>
</div>
</div><br>

<div class="mypage">
<div class="row">
	<div class="col-xs-4 col-xs-offset-2">
		<%= image_tag attachment_url(@user, :profile_image, :fill, 100, 100, format: "jpg", fallback: "no_image.jpg") %>
	</div>
	<div class="poro">
		<% if @user == current_user %>
			<%= link_to "お気に入り", bookmarks_index_path, class: "btn btn-primary" %>
			<%= link_to "プロフィール編集", edit_user_path, class: "btn btn-primary" %>
		<% end %>
	</div>
</div><br>


<div class="row">
	<div class="col-xs-4 col-xs-offset-2">
		<p>名前:<%= @user.name %></p>
		<p>車種:<%= @user.bike_name %></p>
	</div>

	<div class="follow">
		<%= link_to user_follows_path(@user), class: "btn btn-primary" do %>
		フォロー数:<%= @user.follower.count %><br>
		<% end %>
		<%= link_to user_follower_path(@user), class: "btn btn-primary" do %>
		フォロワー数:<%= @user.followed.count %>
		<% end %>
	</div>
</div>
</div>

<div class="row">
	<div class="col-xs-offset-3">
		<h2 class="title col-xs-3">投稿内容</h2>
	</div>
</div><br>

<% @bikes.each do |b| %>
<div class="postlist">
<div class="row">
		<div class="img">
			<%= link_to bike_path(b.id) do %>
			<%= image_tag attachment_url(b, :image, :fill, 500, 500, format: "jpg") %>
			<% end %>
		</div>

		<div class="col-xs-offset-2">
			<!-- コメント -->
			<div class="inline-block">
				<span class="glyphicon glyphicon-comment" aria-hidden="true"></span>
				<%= b.comments.count %>
			</div>
			<!-- いいね -->
			<div class="inline-block" id="likes_area_<%= b.id %>">
				<%= render partial: "likes/like", locals: {like: b, bike: b} %>
			</div>
		</div>

		<div class="col-xs-offset-2">
			<p>ジャンル</p>
			<% b.tags.each do |t| %>
			   ・<%= t.tag_name %>
			<% end %><br>
			<h4>内容</h4>
			<%= b.title %>
		</div><br>

</div>
</div>
<% end %>
<div class="col-xs-offset-3">
	<%= paginate @bikes %>
</div>