config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root  "home#top"
  get  "home/about" => "home#about"
resources :searchs, only: [:index]
resources :users, only: [:index, :show, :edit, :update] do
  	get "follows"
  	get "follower"
  end
  	post "follow/:id" => "relationships#follow", as: "follow"
  	post "unfollow/:id" => "relationships#unfollow", as: "unfollow"

resources :bikes do
	resources :comments, only: [:create, :destroy]
	resource :bookmarks, only: [:create, :destroy]
  resource :likes, only: [:create, :destroy]
end
  get "bookmarks/index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bike.rb
class Bike < ApplicationRecord
	belongs_to :user
	has_many :likes, dependent: :destroy
	has_many :bookmarks, dependent: :destroy
	has_many :comments, dependent: :destroy
	has_many :tagmaps, dependent: :destroy
	has_many :tags, through: :tagmaps
	attachment :image

	validates :image, presence: true
	validates :title, presence: true,length: { maximum: 300 }

	def like_by?(user)
		likes.where(user_id: user.id).exists?
	end

	def bookmark_by?(user)
		bookmarks.where(user_id: user.id).exists?
	end

	def Bike.search(search, user_or_bike)
	    if user_or_bike == "2"
	      Bike.where(["title LIKE ?", "%#{search}%"])
	    else
	      all
	    end
	 end
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :user
  belongs_to :bike
  validates :user_id, uniqueness: {scope: :bike_id}
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :bike
  validates :comment, presence: true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :bike
end

app/models/relationship.rb
class Relationship < ApplicationRecord
	belongs_to :follower, class_name: "User"
	belongs_to :followed, class_name: "User"
end

app/models/tag.rb
class Tag < ApplicationRecord
	has_many :tagmaps, dependent: :destroy
	has_many :bikes, through: :tagmaps
end

app/models/tagmap.rb
class Tagmap < ApplicationRecord
	belongs_to :bike
	belongs_to :tag
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :bikes, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  has_many :bookmarks_bikes, through: :bookmarks, source: :bike
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :following_user, through: :follower, source: :followed
  has_many :follower_user, through: :followed, source: :follower
  attachment :profile_image

 def follow(user_id)
 	follower.create(followed_id: user_id)
 end

 def unfollow(user_id)
 	follower.find_by(followed_id: user_id).destroy
 end

 def following?(user)
 	following_user.include?(user)
 end

 def User.search(search, user_or_bike)
    if user_or_bike == "1"
     User.where(["name LIKE ? OR bike_name LIKE ?", "%#{search}%", "%#{search}%"])
    else
      all
    end
 end

  validates :name, presence: true,length: { minimum: 2, maximum: 20 }
  validates :bike_name, presence: true,length: { minimum: 2, maximum: 20 }

end

app/controllers/bikes_controller.rb
class BikesController < ApplicationController
	before_action :authenticate_user!
	def index
		@bikes = params[:tag_id].present? ? Tag.find(params[:tag_id]).bikes.page(params[:page]).per(5) : Bike.all.includes(:user).page(params[:page]).per(5).order(created_at: :desc)
	end

	def new
		@newbike = Bike.new
	end

	def show
		@bike = Bike.find(params[:id])
		@comment = Comment.new
		@comments = @bike.comments
	end

	def edit
		@bike = Bike.find(params[:id])
		if @bike.user != current_user
			redirect_to bike_path
		end
	end

	def create
		@newbike = Bike.new(bike_params)
		@newbike.user_id = current_user.id
		if @newbike.save
			flash[:notice] = "投稿しました！"
			redirect_to bikes_path
		else
			render :new
		end
	end

	def update
		@bike = Bike.find(params[:id])
		@user = current_user
		if @bike.update(bike_params)
			flash[:notice] = "編集しました！"
			redirect_to bike_path(@bike)
		else
			render :edit
		end
	end

	def destroy
		@bike = Bike.find(params[:id])
		@bike.destroy
		redirect_to bikes_path, notice: "削除しました！"
	end

	private
	def bike_params
		params.require(:bike).permit(:image, :title, tag_ids: [])
	end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def top
	end
	def about
	end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @bike = Bike.find(params[:bike_id])
    @like =current_user.likes.new(bike_id: @bike.id)
    @like.save
    render :like
  end

  def destroy
    @bike = Bike.find(params[:bike_id])
    @like = current_user.likes.find_by(bike_id: @bike.id)
    @like.destroy
    render :like
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bikes_helper.rb
module BikesHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/searchs_helper.rb
module SearchsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_errors.html.erb
<div class="row">
	<div class="col-xs-offset-4">
		<% if obj.errors.any? %>
		    <div id="error_explanation">
		      <h3><%= pluralize(obj.errors.count, "error") %> prohibited this obj from being saved:</h3>

		      <ul>
		      <% obj.errors.full_messages.each do |message| %>
		        <li><%= message %></li>
		      <% end %>
		      </ul>
		    </div>
		<% end %>
	</div>
</div>

app/views/layouts/_footer.html.erb
<footer>
  <div class="container">
  	<div class="row">
    	<div class="col">
    		<p>© 梶ヶ谷　篤哉</p>
    	</div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse" style="margin: 0; padding: 10px 100px" >
    <div class="navbar-header">
      <h1 class="header"><%= link_to "BIKERS", root_path %></h1>
    </div>

    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav navbar-right" style="font-size: 20px; padding-top: 20px;">
        <% if user_signed_in? %>
          <li><%= link_to "マイページ", user_path(current_user)%></li>
          <li><%= link_to "ユーザー一覧", users_path %></li>
          <li><%= link_to "投稿一覧", bikes_path %></li>
          <li><%= link_to "投稿フォーム", new_bike_path %></li>
          <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
          <div class="search col-xs-offset-4">
          <%= form_tag(searchs_path, :method => "get") do %>
          <%= select_tag(:option, options_for_select([["ユーザー", "1"],["投稿内容", "2"]])) %>
          <%= text_field_tag :search %>
          <%= submit_tag "search" %>
          <% end %>
          </div>
          <% else %>
          <li><%= link_to "about", home_about_path %></li>
          <li><%= link_to "ログイン", new_user_session_path %></li>
          <li><%= link_to "新規登録", new_user_registration_path %></li>
        <% end %>
      </ul>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Portfolio</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <div class="body">
      <div class="container-fluid">
      <%= yield %>
      </div>
    </div>
    <%= render "layouts/footer" %>
  </body>
</html>